### ISSUE TITLE
The file is still formatted when `denied_extensions=.*`

### ISSUE THREAD

**Issue by mynkow** [Elders/VSE-FormatDocumentOnSave#11]
Ref=> #9 

I'll create a separate issue for the inheritance part.
I would like to contribute, but I can't promise it will be anytime soon.

Regarding the other issue.
My settings in VS are as follows:
![image](https://user-images.githubusercontent.com/919634/35975309-8d09085c-0cdc-11e8-85f3-3f97ba7db4af.png)

When I then press ctrl + S, the document is formatted.

When I change the extension settings to
![image](https://user-images.githubusercontent.com/919634/35975424-03fed2ac-0cdd-11e8-843e-c56d7af1f821.png)

ctrl + S no longer formats the document.

**Comment by mynkow** [comment]
Fixed in 1.18

**Comment by sergyu91ma** [comment]
This is still happening on VS 2022 on version 3.1. 

![image](https://user-images.githubusercontent.com/6949205/146592367-7fd88011-1c75-472e-ba44-a256d1ebbf43.png)

**Comment by mynkow** [comment]
@sergyu91ma please take a look at [scenario 2](https://github.com/Elders/VSE-FormatDocumentOnSave#scenario-2)
